# =======================================================================
# GitHub Dependabot Configuration
# AquaLytics MVP - Automated Dependency Updates
# =======================================================================

version: 2

updates:
  # ======================
  # FRONTEND DEPENDENCIES
  # ======================
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps-frontend)"
      prefix-development: "chore(deps-dev-frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    reviewers:
      - "aqualytics-team"  # Reemplazar con tu usuario/equipo
    assignees:
      - "aqualytics-team"  # Reemplazar con tu usuario/equipo
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignorar actualizaciones major de Next.js para estabilidad
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      # Ignorar actualizaciones major de React para compatibilidad
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # ======================
  # BACKEND DEPENDENCIES
  # ======================
  - package-ecosystem: "pip"
    directory: "/services/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps-backend)"
      prefix-development: "chore(deps-dev-backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    reviewers:
      - "aqualytics-team"  # Reemplazar con tu usuario/equipo
    assignees:
      - "aqualytics-team"  # Reemplazar con tu usuario/equipo
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Mantener versiones estables para producción
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]

  # ======================
  # GITHUB ACTIONS
  # ======================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps-actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "aqualytics-team"  # Reemplazar con tu usuario/equipo

  # ======================
  # DOCKER DEPENDENCIES
  # ======================
  - package-ecosystem: "docker"
    directory: "/services/api"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps-docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
